name: Stock Data Collection

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual execution

jobs:
  collect-stock-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install schedule requests

      - name: Run Stock Data Collection Script
        run: python multiple_stocks_data_collector.py

      - name: Commit and Push CSV File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add multiple_stocks_data.csv
          git commit -m "Updated stock data"
          git push
        continue-on-error: true
